name: Deploy to Cloudflare Pages (MVP Frontend-First)

# MVP Strategy: Deploy frontend independently for faster iteration
# Backend will be deployed separately to Google Cloud Run
on:
  push:
    branches: [main, master]
    paths: 
      - 'index.html'
      - 'components/**'
      - 'assets/**'
      - 'wrangler.toml'
      - '.github/workflows/cloudflare-pages.yml'
  pull_request:
    branches: [main, master]
    paths:
      - 'index.html' 
      - 'components/**'
      - 'assets/**'
      - 'wrangler.toml'
  workflow_dispatch:
    inputs:
      backend_url:
        description: 'Backend URL to use for API calls'
        required: false
        default: 'https://seo-audit-backend-YOUR_PROJECT_ID.a.run.app'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Frontend to Cloudflare Pages
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Wrangler CLI
        run: npm install -g wrangler
        
      - name: Run tests
        run: npm test
        env:
          NODE_ENV: test
        continue-on-error: false
        
      - name: Install dependencies for frontend build
        run: npm install
        
      - name: Build Tailwind CSS for production
        run: |
          if [ -f "tailwind.config.js" ]; then
            npx tailwindcss -i ./index.html -o ./styles.css --minify
            echo "✓ Tailwind CSS built for production"
          else
            echo "No Tailwind config found, skipping CSS build"
          fi
        
      - name: Create build directory
        run: mkdir -p dist
        
      - name: Copy frontend files
        run: |
          cp index.html dist/
          
          # Ensure components directory is copied (required for AttentionComponents)
          if [ -d "components" ]; then
            cp -r components/ dist/
            echo "✓ Components directory copied"
          else
            echo "⚠️  ERROR: components/ directory not found - this will cause MIME type errors"
            exit 1
          fi
          
          # Copy assets if they exist
          if [ -d "assets" ]; then
            cp -r assets/ dist/
            echo "✓ Assets directory copied"
          else
            echo "No assets directory (optional)"
          fi
          
      - name: Configure backend URL
        env:
          BACKEND_URL: ${{ github.event.inputs.backend_url || secrets.BACKEND_URL || 'https://seo-audit-backend-YOUR_PROJECT_ID.a.run.app' }}
        run: |
          if [ "$BACKEND_URL" != "https://seo-audit-backend-YOUR_PROJECT_ID.a.run.app" ]; then
            sed -i "s|http://localhost:3001|$BACKEND_URL|g" dist/index.html
            sed -i "s|http://localhost:8080|$BACKEND_URL|g" dist/index.html
            sed -i "s|http://127.0.0.1:3001|$BACKEND_URL|g" dist/index.html
            sed -i "s|http://127.0.0.1:8080|$BACKEND_URL|g" dist/index.html
            echo "✅ Updated API endpoints to: $BACKEND_URL"
          else
            echo "⚠️ Using placeholder backend URL"
          fi
          
      - name: Update wrangler.toml with backend URL
        env:
          BACKEND_URL: ${{ github.event.inputs.backend_url || secrets.BACKEND_URL || 'https://seo-audit-backend-YOUR_PROJECT_ID.a.run.app' }}
        run: |
          if [ "$BACKEND_URL" != "https://seo-audit-backend-YOUR_PROJECT_ID.a.run.app" ]; then
            sed -i "s|https://seo-audit-backend-YOUR_PROJECT_ID.a.run.app|$BACKEND_URL|g" wrangler.toml
          fi
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=seo-audit-tool --compatibility-date=2024-08-24
          
      - name: Deployment Success
        run: |
          echo "✅ Frontend deployed successfully to Cloudflare Pages"
          echo "🌐 URL: https://seo-audit-tool.pages.dev"
          echo "📝 Commit: ${{ github.sha }}"
            
            
  # Health check after deployment  
  health-check:
    needs: deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
      - name: Wait for deployment
        run: sleep 30
        
      - name: Check frontend health
        run: |
          curl -f https://seo-audit-tool.pages.dev/ || exit 1
          echo "✅ Frontend is responding"
          
      - name: Check backend health (if configured)
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        if: env.BACKEND_URL != ''
        run: |
          curl -f $BACKEND_URL/api/health || exit 1
          echo "✅ Backend is responding"