name: Deploy to Cloudflare Pages (MVP Frontend-First)

# MVP Strategy: Deploy frontend independently for faster iteration
# Backend will be deployed separately to Google Cloud Run
on:
  push:
    branches: [main, master]
    paths: 
      - 'index.html'
      - 'components/**'
      - 'assets/**'
      - 'wrangler.toml'
      - '.github/workflows/cloudflare-pages.yml'
      - 'src/**'
      - 'dist/**'
      - '_headers'
      - 'tailwind.config.js'
      - 'postcss.config.js'
      - 'package.json'
  pull_request:
    branches: [main, master]
    paths:
      - 'index.html' 
      - 'components/**'
      - 'assets/**'
      - 'wrangler.toml'
      - 'src/**'
      - 'dist/**'
      - '_headers'
      - 'tailwind.config.js'
      - 'postcss.config.js'
      - 'package.json'
  workflow_dispatch:
    inputs:
      backend_url:
        description: 'Backend URL to use for API calls'
        required: false
        default: 'https://seo-audit-backend-YOUR_PROJECT_ID.a.run.app'
      force_deploy:
        description: 'Force deployment (bypass tests)'
        required: false
        default: 'false'
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Frontend to Cloudflare Pages
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Wrangler CLI
        run: npm install -g wrangler@latest
        
      - name: Build production assets
        run: |
          npm run build:prod
          echo "✓ Production assets built"
          
      - name: Configure backend URL
        env:
          BACKEND_URL: ${{ github.event.inputs.backend_url || secrets.BACKEND_URL || 'https://seo-audit-backend-YOUR_PROJECT_ID.a.run.app' }}
        run: |
          if [ "$BACKEND_URL" != "https://seo-audit-backend-YOUR_PROJECT_ID.a.run.app" ]; then
            sed -i "s|http://localhost:3001|$BACKEND_URL|g" dist/index.html
            sed -i "s|http://localhost:8080|$BACKEND_URL|g" dist/index.html
            sed -i "s|http://127.0.0.1:3001|$BACKEND_URL|g" dist/index.html
            sed -i "s|http://127.0.0.1:8080|$BACKEND_URL|g" dist/index.html
            echo "✅ Updated API endpoints to: $BACKEND_URL"
          else
            echo "⚠️ Using placeholder backend URL"
          fi
          
      - name: Update wrangler.toml with backend URL
        env:
          BACKEND_URL: ${{ github.event.inputs.backend_url || secrets.BACKEND_URL || 'https://seo-audit-backend-YOUR_PROJECT_ID.a.run.app' }}
        run: |
          if [ "$BACKEND_URL" != "https://seo-audit-backend-YOUR_PROJECT_ID.a.run.app" ]; then
            sed -i "s|https://seo-audit-backend-YOUR_PROJECT_ID.a.run.app|$BACKEND_URL|g" wrangler.toml
          fi
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=seo-audit-tool-e50
          
      - name: Deployment Success
        run: |
          echo "✅ Frontend deployed successfully to Cloudflare Pages"
          echo "🌐 URL: https://seo-audit-tool.pages.dev"
          echo "📝 Commit: ${{ github.sha }}"
            
            
  # Health check after deployment  
  health-check:
    needs: deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
      - name: Wait for deployment
        run: sleep 30
        
      - name: Check frontend health
        run: |
          curl -f https://seo-audit-tool.pages.dev/ || exit 1
          echo "✅ Frontend is responding"
          
      - name: Check backend health (if configured)
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        if: env.BACKEND_URL != ''
        run: |
          curl -f $BACKEND_URL/api/health || exit 1
          echo "✅ Backend is responding"